export default {
    NAVIGATE: 'NAVIGATE',
    LOGOUT: 'LOGOUT',
    SET_AUTHENTICATED_USER: 'SET_AUTHENTICATED_USER',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR',
    LOGOUT_USER: 'LOGOUT_USER',

    SOCKET_CONNECT: 'SOCKET_CONNECT',
    SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',

    
    // Promise middleware
    FULFILLED: '_FULFILLED',
    PENDING: '_PENDING',
    REJECTED: '_REJECTED',
};
